### ISSUE TITLE
mesonconf is deprecated

### ISSUE THREAD

**Issue by DroWnThePoor** [robertsanseries/ciano#12]
When following your instructions I get 
~/Git/Dload/ciano/build$ mesonconf -Dprefix=/usr
Warning: This executable is deprecated. Use "meson configure" instead.
so I tried
~/Git/Dload/ciano/build$ meson configure -Dprefix/usr
Meson configurator encountered an error:
Value "prefix/usr" not of type "a=b"
I'm sorry, not familiar with these tools.
I'm on eOS Loki.

**Comment by robertsanseries** [comment]
LoL

The message:

```Warning: This executable is deprecated. Use "meson configure" instead. just tried```

It's just a warning that there is this new option! You can continue the installation!

however, if you wanted to use the new option:

```meson configure -Dprefix=/usr```


_Did you forget to use the "=" sign_ :D
