### ISSUE TITLE
Brand colors do not pass color contrast check

### ISSUE THREAD

**Issue by danrabbit** [robertsanseries/ciano#21]
https://github.com/robertsanseries/ciano/blob/29ae515e8f6a449622e40743fdf80ba9d228358f/data/com.github.robertsanseries.ciano.appdata.xml#L36

Colors should ideally [pass WCAG AA color contrast standard](https://snook.ca/technical/colour_contrast/colour.html#fg=34CACA,bg=8CD5FF)

**Comment by robertsanseries** [comment]
@danrabbit  Thanks for the tip! 

Now it will look like this:

```
<value key="x-appcenter-color-primary">#52D3D2</value>
<value key="x-appcenter-color-primary-text">#000000</value>
```

![captura de tela de 2017-09-21 10-43-14](https://user-images.githubusercontent.com/11967501/30698995-e4ecbd98-9eb9-11e7-8333-abaa3c92edde.png)


(exemple)
![captura de tela de 2017-09-21 09-59-53](https://user-images.githubusercontent.com/11967501/30698729-2860f356-9eb9-11e7-924d-90fba04d66e4.png)


Commit 6462e4a390774c20062bcc1766e07ddd9f01372b
