### ISSUE TITLE
Remove frames from main widgets

### ISSUE THREAD

**Issue by donadigo** [robertsanseries/ciano#23]
Just make the convert sidebar and the main view expand over to the entire window rather than having them each in a Gtk.Frame.

**Comment by robertsanseries** [comment]
@donadigo Sorry but I did not understand!

**Comment by donadigo** [comment]
I mean remove `Gtk.Frame`s and margins from your `ConverterView` so that the source list sidebar and job list view fit the entire window rather than being put inside smaller containers. I will make a screenshot for you tomorrow to show what I mean.

**Comment by robertsanseries** [comment]
Change made

commit a34395cf2a3ede8ea793d5f586c17b6c28e63ddd
