### ISSUE TITLE
Preferences dialog labels

### ISSUE THREAD

**Issue by donadigo** [robertsanseries/ciano#25]
You have a typo in "Erro notify", I guess it should be "Error notify"?

I would also suggest using more explicit explanations for the preferences like:
"Notify about completed action: <switch>"
"Notify about an error: <switch>"

"Notify" header to just "Notifications".

I would also swap the vertical position of the output folder options so that the "Select output folder" becomes the option at the top and "Output to source file folder" at the bottom. It seems more logical to first choose if you want to have a different save location and then to actually choose it.

**Comment by robertsanseries** [comment]
@donadigo Thank you for the tips!


commit 9b40e6273c39a761252f4123ec28ea0ecb679799
