### ISSUE TITLE
OGV videos aren't selectable

### ISSUE THREAD

**Issue by cassidyjames** [robertsanseries/ciano#28]
Screen recorders frequently output ogv, but with Ciano I can't open them i.e. to convert to mp4.

**Comment by robertsanseries** [comment]
@cassidyjames  Unfortunately it only supports selecting the formats that the application can convert. I will try to include support for OGV format.

**Comment by robertsanseries** [comment]
@cassidyjames  Sorry for the delay!

Added support, coming soon in AppCenter.
