### ISSUE TITLE
Video to GIF

### ISSUE THREAD

**Issue by cassidyjames** [robertsanseries/ciano#29]
It'd be awesome to recognize GIF as an output format for video

**Comment by robertsanseries** [comment]
@cassidyjames  Initially I added it, however it was generating some errors. I will add and try to resolve these errors!

**Comment by robertsanseries** [comment]
@cassidyjames Sorry for the delay!

Added support, coming soon in AppCenter.

Commit 3093da5fbb3ba3441caa725c95f8ad66f674e941
