### ISSUE TITLE
Does not convert video to audio?

### ISSUE THREAD

**Issue by Gabriel-p** [robertsanseries/ciano#32]
I just tried converting an mp4 to mp3 (extract audio), but if I select `Convert to MP3` then the `mp4` files can not be selected.

**Comment by robertsanseries** [comment]
@Gabriel-p This is something I'm already working on trying to release this weekend.

**Comment by robertsanseries** [comment]
@Gabriel-p Sorry for the delay!

Added support, coming soon in AppCenter.

Commit 6748ec3112f9821c10c9596c639ab336c460fe1e
