### ISSUE TITLE
Conversion from mov to mp4 does not work

### ISSUE THREAD

**Issue by Corsseir** [robertsanseries/ciano#33]
Hey,

first of all thank you for this great app, unfortunately conversion from mov to mp4 does not work:

```
corsseir@LTC0:~$ com.github.robertsanseries.ciano

(com.github.robertsanseries.ciano:16583): Gtk-CRITICAL **: gtk_file_filter_get_name: assertion 'GTK_IS_FILE_FILTER (filter)' failed

** (com.github.robertsanseries.ciano:16583): WARNING **: ConverterController.vala:280: Error: Child process exited with code 1
```

![screenshot from 2017-10-11 12-47-39](https://user-images.githubusercontent.com/11137173/31436179-675b4132-ae82-11e7-9230-be166e0dde56.png)

**Comment by robertsanseries** [comment]
Hi @Corsseir,

Sorry for the delay to answer you. 

Please could you test with another video only to confirm if there is no error in the video used? I tested it with 5 random videos and it worked normally.

If you want to confirm that the error is from the application, perform the following test via terminal:
`` `ffmpeg -y -i namevideo.mov -strict -2 namevideo.mp4```

**Comment by robertsanseries** [comment]
Issue closed porque I can not reproduce the error. If the user wishes, he can reopen the question.
