### ISSUE TITLE
Text in the sidebar is being cut off.

### ISSUE THREAD

**Issue by Djcoper** [robertsanseries/ciano#34]
![screenshot from 2017-10-16 05 21 01](https://user-images.githubusercontent.com/30577249/31595205-dcbaf7bc-b231-11e7-8941-77977d3c7a5a.png)

**Comment by robertsanseries** [comment]
@Djcoper  I increased the width of the side menu to follow the standard size of the applications of elementary OS (File, Scratch ...).

Coming soon in AppCenter.

Commit 4489dfec7dcfe2ef1fd5f93bb78f3493e2f396d8
