### ISSUE TITLE
Don't write directly on the home folder

### ISSUE THREAD

**Issue by Philip-Scott** [robertsanseries/ciano#39]
The default output directory shouldn't be a folder on your home. 

You should write by default to `~/.local/share/ciano`

**Comment by robertsanseries** [comment]
@Philip-Scott If the user needs to get the output file later, this would force him to open the application. or the default should be in the ~ / .local / share / cyan directory ??

**Comment by robertsanseries** [comment]
Coming soon in the appcenter. Thanks for the tip! :man_dancing:
