### ISSUE TITLE
zh_CN.po

### ISSUE THREAD

**Issue by trampover** [robertsanseries/ciano#46]
msgid ""
msgstr ""
"Project-Id-Version: com.github.robertsanseries.ciano\n"
"POT-Creation-Date: 2017-09-14 22:30-0000\n"
"PO-Revision-Date: 2017-12-06 09:46-0000\n"
"Last-Translator:  金立龙 <trampover@gmail.com>\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: src/configs/Properties.vala:31
msgid "Convert file"
msgstr "文件转换"

#: src/configs/Properties.vala:33
msgid "Convert file to"
msgstr "文件转换为"

#: src/configs/Properties.vala:35
msgid "Name"
msgstr "名称"

#: src/configs/Properties.vala:37
msgid "Add items to conversion:"
msgstr "选择需要转换得文件:"

#: src/configs/Properties.vala:39
msgid "Directory"
msgstr "目录"

#: src/configs/Properties.vala:41
msgid "Add file"
msgstr "添加"

#: src/configs/Properties.vala:43
msgid "Delete"
msgstr "删除"

#: src/configs/Properties.vala:45
msgid "Cancel"
msgstr "取消"

#: src/configs/Properties.vala:47
msgid "Start conversion"
msgstr "开始转换"

#: src/configs/Properties.vala:49
msgid "Output folder:"
msgstr "输出目录:"

#: src/configs/Properties.vala:51
msgid "Files origin:"
msgstr "文件来源:"

#: src/configs/Properties.vala:53
msgid "Select the output folder:"
msgstr "选择输出文件夹:"

#: src/configs/Properties.vala:55
msgid "Notifications:"
msgstr "消息通知:"

#: src/configs/Properties.vala:57
msgid "Notify about completed action:"
msgstr "转换完成显示通知消息:"

#: src/configs/Properties.vala:59
msgid "Notify about an error:"
msgstr "转换错误显示通知消息:"

#: src/configs/Properties.vala:61
msgid "Close"
msgstr "关闭"

#: src/configs/Properties.vala:63
msgid "Open output folder"
msgstr "打开输出目录"

#: src/configs/Properties.vala:65
msgid "Settings"
msgstr "设置"

#: src/configs/Properties.vala:67
msgid "Preferences"
msgstr "偏好设置"

#: src/configs/Properties.vala:69
msgid "Empty conversion list"
msgstr "清空转换列表"

#: src/configs/Properties.vala:71
msgid "Select an option from the side menu to which you want to \n convert your file"
msgstr "从侧边菜单中选择 \n 一个选项到要转换的文件"

#: src/configs/Properties.vala:73
msgid "Starting..."
msgstr "进行中..."

#: src/configs/Properties.vala:75
msgid "Cancel conversion"
msgstr "取消转换"

#: src/configs/Properties.vala:77
msgid "Remove"
msgstr "删除"

#: src/configs/Properties.vala:79
msgid "Remove item from list"
msgstr "从列表中删除项目"

#: src/configs/Properties.vala:81
msgid "Video"
msgstr "视频"

#: src/configs/Properties.vala:83
msgid "Music"
msgstr "音乐"

#: src/configs/Properties.vala:85
msgid "Image"
msgstr "图片"

#: src/configs/Properties.vala:87
msgid "Select file"
msgstr "选择文件"

#: src/configs/Properties.vala:89
msgid "Add"
msgstr "添加"

#: src/configs/Properties.vala:91
msgid "Conversion completed"
msgstr "转换完成"

#: src/configs/Properties.vala:93
msgid "Conversion canceled"
msgstr "转换取消"

#: src/configs/Properties.vala:95
msgid "Error in conversion"
msgstr "转换中出现的错误"

#: src/configs/Properties.vala:97
msgid "percentage: "
msgstr "已完成: "

#: src/configs/Properties.vala:99
msgid " - size: "
msgstr " - 大小: "

#: src/configs/Properties.vala:101
msgid " - time: "
msgstr " - 时间: "

#: src/configs/Properties.vala:103
msgid " - bitrate: "
msgstr " - 码率: "

#: src/configs/Properties.vala:105
msgid "Error: experimental codecs are not enabled"
msgstr "错误: 找不到解码器"

#: src/configs/Properties.vala:107
msgid "Error: invalid data found when processing input"
msgstr "错误: 需要转换的文件不存在或文件路径错误"

#: src/configs/Properties.vala:109
msgid "Error: No such file or directory"
msgstr "错误: 没有这个文件或目录"

#: src/configs/Properties.vala:111
msgid "Error: Invalid argument"
msgstr "错误: 转换参数无效"

#: data/com.github.robertsanseries.ciano.desktop.in:3
#: data/com.github.robertsanseries.ciano.appdata.xml.in:8
msgid "A multimedia file converter"
msgstr "多媒体文件转换器"

#: data/com.github.robertsanseries.ciano.appdata.xml.in:19
msgid "The easiest way to convert your multimedia files to the most popular formats."
msgstr "最简单的方式转换为您的多媒体文件转换为其它的格式."

#: data/com.github.robertsanseries.ciano.appdata.xml.in:20
msgid "Characteristics:"
msgstr "特点"

#: data/com.github.robertsanseries.ciano.appdata.xml.in:22
msgid "Conversion of multiple files at the same time"
msgstr "同时转换多个文件"

#: data/com.github.robertsanseries.ciano.appdata.xml.in:23
msgid "Possibility of changing the output folder"
msgstr "更改输出文件夹"

#: data/com.github.robertsanseries.ciano.appdata.xml.in:24
msgid "Notification support"
msgstr "通知支持"

#: data/com.github.robertsanseries.ciano.appdata.xml.in:25
msgid "Close the application at any time with Ctrl + Q"
msgstr "快速关闭Ciano快捷键 Ctrl+Q"

#: data/com.github.robertsanseries.ciano.appdata.xml.in:27
msgid "Supports the conversion of:"
msgstr "支持转换的文件格式:"

#: data/com.github.robertsanseries.ciano.appdata.xml.in:29
msgid "Video - MP4, MPG, AVI, WMV, FLV, MKV, 3GP, MOV, VOB, OGV, WEBM"
msgstr "Vídeo - MP4, MPG, AVI, WMV, FLV, MKV, 3GP, MOV, VOB, OGV, WEBM"

#: data/com.github.robertsanseries.ciano.appdata.xml.in:30
msgid "Audio - MP3, WMA, OGG, WAV, AAC, FLAC, AIFF, MMF, M4A"
msgstr "Audio - MP3, WMA, OGG, WAV, AAC, FLAC, AIFF, MMF, M4A"

#: data/com.github.robertsanseries.ciano.appdata.xml.in:31
msgid "Images - JPG, BMP, PNG, TIF, GIF, TGA"
msgstr "Imagens - JPG, BMP, PNG, TIF, GIF, TGA"

**Comment by robertsanseries** [comment]
@trampover Thank you very much for the contribution!
