### ISSUE TITLE
can't convert MPEG-4 videos with ciano.

### ISSUE THREAD

**Issue by Maccer1** [robertsanseries/ciano#47]
I have some files from my previous phone that I want to convert but I'm unable to do it because ciano doesn't seem to detect them. Those files are .mp4, [here](https://drive.google.com/open?id=1ovkEai9xgLm4DJuyngW2bKu9DK-zespa) you have an example if you want to try to convert it.

Doesn't matter if I drag and drop the file or try to find it with the browser, it doesn't detect it.

**Comment by robertsanseries** [comment]
@Maccer1 Sorry for the delay, it was college! 

I can not reproduce your problem!

More I ended up finding another conversion error that would be conrrigido in issue #48

**Comment by Maccer1** [comment]
Oops my bad.. I should've read it correctly. It says "convert file to" not "convert from".. I was selecting MP4 so that's why I couldn't see the archive.. it was already on MP4 format lol.

Well, if you solved that error already you can close this bug.. Sorry for the trouble

**Comment by robertsanseries** [comment]
@Maccer1 I'll close this report! the error will be fixed in the next version 0.1.9 (Friday).

Thanks and Happy New Year!
