### ISSUE TITLE
could you make a flatpak for ciano?

### ISSUE THREAD

**Issue by altntowin** [robertsanseries/ciano#50]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for ciano?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by robertsanseries** [comment]
@altntowin  A flatpak version is already available on flathub, but I was not able to test all the features.

https://github.com/flathub/com.github.robertsanseries.ciano

In case you encounter any problems, you could report it here in the issues.
