### ISSUE TITLE
Download and convert videos from Youtube, HTTP and other web sources

### ISSUE THREAD

**Issue by moqmar** [robertsanseries/ciano#60]
That would be a nice-to-have feature in the future, it makes sense in my opinion to combine the downloader and converter as the download quality for e.g. YouTube could depend on the selected output codec.

**Comment by robertsanseries** [comment]
Apps should not violate laws or terms of conditions of third-party services they utilize.

As you can see here [App Karim - Issue 21](https://github.com/robertsanseries/karim/issues/21)
