### ISSUE TITLE
file bug for libgda update in vala

### ISSUE THREAD

**Issue by kvdz** [robertsanseries/ciano#9]
vapi files are not the way to go. file a issue to vala to add the wanted version of libgda.

vapi's are only a resource when nothing else is possible at the moment.

**Comment by robertsanseries** [comment]
@kvdz  Libgda removed. The use will no longer be necessary in this final version! 

Thank you very much for the contribution!

Commit 46c8e25a0a6832be0bffcfd5763fa459e8c7c04f
